<?php

/**
 * Register ACF Field Groups and Options Pages.
 */
function vcl_register_acf_fields_and_options() {
	// Make sure ACF is available.
	if ( ! function_exists( 'acf_add_local_field_group' ) || ! function_exists( 'acf_add_options_page' ) ) {
		return;
	}

	// Register Field Groups
	acf_add_local_field_group( array(
		'key' => 'group_684bad8a03a71',
		'title' => 'Homepage settings',
		'fields' => array(
			array(
				'key' => 'field_684baece2b525',
				'label' => 'Banners',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67a5b6201f810',
				'label' => 'Main banner',
				'name' => 'main_banner',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 1,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_67a5b6a31f811',
						'label' => 'Banner image',
						'name' => 'banner_image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'allow_in_bindings' => 0,
						'preview_size' => 'medium',
						'parent_repeater' => 'field_67a5b6201f810',
					),
					array(
						'key' => 'field_67a5b6b91f812',
						'label' => 'Banner URL',
						'name' => 'banner_url',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'allow_in_bindings' => 0,
						'parent_repeater' => 'field_67a5b6201f810',
					),
				),
			),
			array(
				'key' => 'field_67a5b72d1f813',
				'label' => 'Sub Banner',
				'name' => 'sub_banner',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_67a5b7611f814',
						'label' => 'Icon',
						'name' => 'icon',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'allow_in_bindings' => 0,
						'preview_size' => 'thumbnail',
						'parent_repeater' => 'field_67a5b72d1f813',
					),
					array(
						'key' => 'field_67a5b77f1f815',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_67a5b72d1f813',
					),
					array(
						'key' => 'field_67a5b7911f816',
						'label' => 'Description',
						'name' => 'description',
						'aria-label' => '',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'rows' => 3,
						'placeholder' => '',
						'new_lines' => '',
						'parent_repeater' => 'field_67a5b72d1f813',
					),
					array(
						'key' => 'field_67ad60f1f9ba9',
						'label' => 'URL',
						'name' => 'url',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'allow_in_bindings' => 0,
						'parent_repeater' => 'field_67a5b72d1f813',
					),
				),
			),
			array(
				'key' => 'field_67a5b86e4e372',
				'label' => 'Service Box',
				'name' => 'service_box',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 4,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_67a5b8a04e373',
						'label' => 'Icon',
						'name' => 'icon',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'allow_in_bindings' => 0,
						'preview_size' => 'thumbnail',
						'parent_repeater' => 'field_67a5b86e4e372',
					),
					array(
						'key' => 'field_67a5b8df4e374',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_67a5b86e4e372',
					),
				),
			),
			array(
				'key' => 'field_67a5c16ad3320',
				'label' => 'Ads Banner',
				'name' => 'ads_banner',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 3,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_67a5c1bdd3321',
						'label' => 'Image',
						'name' => 'image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'allow_in_bindings' => 0,
						'preview_size' => 'thumbnail',
						'parent_repeater' => 'field_67a5c16ad3320',
					),
					array(
						'key' => 'field_67a5c1c8d3322',
						'label' => 'Banner URL',
						'name' => 'banner_url',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'allow_in_bindings' => 0,
						'parent_repeater' => 'field_67a5c16ad3320',
					),
				),
			),
			array(
				'key' => 'field_684baef52b526',
				'label' => 'Body',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67a5b98ba46c9',
				'label' => 'Gift Voucher section',
				'name' => 'gift_voucher_section',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'allow_in_bindings' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_67a5b9d3a46ca',
				'label' => 'Gift voucher',
				'name' => 'gift_voucher',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '90',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_67a5ba05a46cb',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_67a5baf6a46cc',
						'label' => 'Description',
						'name' => 'description',
						'aria-label' => '',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'rows' => 2,
						'placeholder' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_67a5bb0aa46cd',
						'label' => 'Button label',
						'name' => 'button_label',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_67a5bb19a46ce',
						'label' => 'Button URL',
						'name' => 'button_url',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'allow_in_bindings' => 0,
					),
				),
			),
			array(
				'key' => 'field_67a5bd720e676',
				'label' => 'FlashSale section',
				'name' => 'flashsale_section',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'allow_in_bindings' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_684baf3b99a3b',
				'label' => 'Products & News',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_684ba92f4dccc',
				'label' => 'New products',
				'name' => 'new_products',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'pro_cate',
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'object',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_67b49cfb5ac09',
				'label' => 'Category section',
				'name' => 'category_box',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_67b49e71a5ff2',
						'label' => 'Box title',
						'name' => 'box_title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_67b49cfb5ac09',
					),
					array(
						'key' => 'field_67b49e78a5ff3',
						'label' => 'Select category',
						'name' => 'select_category',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'pro_cate',
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'object',
						'field_type' => 'multi_select',
						'allow_null' => 0,
						'allow_in_bindings' => 0,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_67b49cfb5ac09',
					),
					array(
						'key' => 'field_68667dfd71a4d',
						'label' => 'View more button',
						'name' => 'view_more_button',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_67b49cfb5ac09',
					),
					array(
						'key' => 'field_68667e2c71a4e',
						'label' => 'View more URL',
						'name' => 'view_more_url',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'allow_in_bindings' => 1,
						'placeholder' => '',
						'parent_repeater' => 'field_67b49cfb5ac09',
					),
				),
			),
			array(
				'key' => 'field_6818454a4858a',
				'label' => 'News section',
				'name' => 'news_section',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_681845684858e',
						'label' => 'Section title',
						'name' => 'section_title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_681845864858f',
						'label' => 'News category',
						'name' => 'news_category',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'category',
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'object',
						'field_type' => 'multi_select',
						'allow_null' => 0,
						'allow_in_bindings' => 0,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(
						),
					),
					array(
						'key' => 'field_6818463348590',
						'label' => 'Review category',
						'name' => 'review_category',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'category',
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'object',
						'field_type' => 'select',
						'allow_null' => 0,
						'allow_in_bindings' => 0,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(
						),
					),
				),
			),
			array(
				'key' => 'field_6865000142a5b',
				'label' => 'Brands',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_68650134a1bfe',
				'label' => 'Section title',
				'name' => 'brands_section_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6865005b42a5c',
				'label' => 'Select brands',
				'name' => 'select_brands',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'brands',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 1,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'homepage',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_67a97b05468cb',
		'title' => 'Page option',
		'fields' => array(
			array(
				'key' => 'field_67a97b0557674',
				'label' => 'Show Breadcrumb',
				'name' => 'show_breadcrumb',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'allow_in_bindings' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_67a97b4057675',
				'label' => 'Show Page title',
				'name' => 'show_page_title',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'allow_in_bindings' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_67a57c98901ad',
		'title' => 'Register and Login',
		'fields' => array(
			array(
				'key' => 'field_67a57c973dd61',
				'label' => 'Login content',
				'name' => 'login_content',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => 'Content for left Column',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 1,
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-register.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6777606f6a0a1',
		'title' => 'Site Configs',
		'fields' => array(
			array(
				'key' => 'field_6777606e50527',
				'label' => 'Main Configs',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_6777649a1440d',
				'label' => 'Site logo',
				'name' => 'site-logo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'thumbnail',
			),
			array(
				'key' => 'field_686674feea6e1',
				'label' => 'Search suggestions',
				'name' => 'search_suggestions',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'allow_in_bindings' => 0,
				'ui_on_text' => 'On',
				'ui_off_text' => 'Off',
				'ui' => 1,
			),
			array(
				'key' => 'field_677760b250528',
				'label' => 'Hotline',
				'name' => 'site-hotline',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67ab1f18927d6',
				'label' => 'Header hotline 1 - Label',
				'name' => 'header_hotline_1_label',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67ab1ef3927d5',
				'label' => 'Header hotline 1',
				'name' => 'header_hotline_1',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67ab1f50927d9',
				'label' => 'Header hotline 2 - Label',
				'name' => 'header_hotline_2_label',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67ab1f3d927d7',
				'label' => 'Header hotline 2',
				'name' => 'header_hotline_2',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67ab1f6e927db',
				'label' => 'Header hotline 3 - Label',
				'name' => 'header_hotline_3_label',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67ab1f69927da',
				'label' => 'Header hotline 3',
				'name' => 'header_hotline_3',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6777613750529',
				'label' => 'Email',
				'name' => 'site-email',
				'aria-label' => '',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6803153d4c4e4',
				'label' => 'Checkout privacy policy',
				'name' => 'checkout_privacy_policy',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'rows' => 3,
				'placeholder' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_677761e048226',
				'label' => 'Socials',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67a337026a702',
				'label' => 'Youtube',
				'name' => 'youtube_url',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67a337216a703',
				'label' => 'Facebook',
				'name' => 'facebook_url',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67a337306a704',
				'label' => 'Instagram',
				'name' => 'instagram_url',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67a33541f35af',
				'label' => 'Default page',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_68036271015b2',
				'label' => 'Shop page',
				'name' => 'shop_page',
				'aria-label' => '',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'allow_archives' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_67a33565f35b0',
				'label' => 'Store system',
				'name' => 'store_system',
				'aria-label' => '',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'allow_archives' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_67a335cbf35b1',
				'label' => 'Tracking order',
				'name' => 'tracking_order',
				'aria-label' => '',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'allow_archives' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_67a335f6f35b2',
				'label' => 'Register & Login',
				'name' => 'register_and_login',
				'aria-label' => '',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'allow_archives' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_67a33625f35b3',
				'label' => 'Shopping cart',
				'name' => 'shopping_cart',
				'aria-label' => '',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'allow_archives' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_67a3364bf35b4',
				'label' => 'User account',
				'name' => 'user_account',
				'aria-label' => '',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'allow_archives' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_67a337c11d240',
				'label' => 'Footer',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67a3397d75b0d',
				'label' => 'Footer logo',
				'name' => 'footer_logo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'thumbnail',
			),
			array(
				'key' => 'field_677764eb1440e',
				'label' => 'Copyright text',
				'name' => 'copyright_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67a337f61d242',
				'label' => 'Business license',
				'name' => 'business_license',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 1,
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_67a337cf1d241',
				'label' => 'Logo BCT',
				'name' => 'logo_bct',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'thumbnail',
			),
			array(
				'key' => 'field_67f898fe3cc6c',
				'label' => 'BCT Url',
				'name' => 'bct_url',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67a338341d243',
				'label' => 'Logo BCT 2',
				'name' => 'logo_bct_2',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_67f899483cc6d',
				'label' => 'BCT Url 2',
				'name' => 'bct_url_2',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67a338571d244',
				'label' => 'Logo BCT 3',
				'name' => 'logo_bct_3',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_67f899633cc6e',
				'label' => 'BCT Url 3',
				'name' => 'bct_url_3',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67a338fe1d245',
				'label' => 'Logo protected',
				'name' => 'logo_protected',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'thumbnail',
			),
			array(
				'key' => 'field_67a339261d246',
				'label' => 'Protected url',
				'name' => 'protected_url',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67a771b1a330c',
				'label' => 'Products',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67a771daa330d',
				'label' => 'Products per page',
				'name' => 'products_per_page',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 12,
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_67ce5eb3441b3',
				'label' => 'Connections',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67ce608f441b4',
				'label' => 'ERP API',
				'name' => 'erp_api',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_67ce60ad441b5',
						'label' => 'Domain',
						'name' => 'domain',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_67ce60bd441b6',
						'label' => 'API Key',
						'name' => 'api_key',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_67ce60c7441b7',
						'label' => 'API Secret',
						'name' => 'api_secret',
						'aria-label' => '',
						'type' => 'password',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_689771470522c',
						'label' => 'Update Order status endpoint',
						'name' => 'update_order_status_endpoint',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_6896b94d1b5a8',
				'label' => 'Payoo API',
				'name' => 'payoo_api',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '70',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_6896ba6b1b5b3',
						'label' => 'Current use',
						'name' => 'current_use',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'allow_in_bindings' => 0,
						'ui_on_text' => 'Production',
						'ui_off_text' => 'Sanbox',
						'ui' => 1,
					),
					array(
						'key' => 'field_6896c0ae1539a',
						'label' => 'Debug log',
						'name' => 'debug_log',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'allow_in_bindings' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
					),
					array(
						'key' => 'field_6896b97a1b5a9',
						'label' => 'Production',
						'name' => 'production',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6896b9911b5aa',
								'label' => 'Merchant\'s username',
								'name' => 'username',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'allow_in_bindings' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_6896b9be1b5ab',
								'label' => 'Merchant\'s Id',
								'name' => 'merchants_id',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'allow_in_bindings' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_6896b9da1b5ac',
								'label' => 'Checksum key',
								'name' => 'checksum_key',
								'aria-label' => '',
								'type' => 'password',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'allow_in_bindings' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_6896ba1e1b5ad',
								'label' => 'Url checkout',
								'name' => 'url_checkout',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'allow_in_bindings' => 0,
								'placeholder' => '',
							),
						),
					),
					array(
						'key' => 'field_6896ba4d1b5ae',
						'label' => 'Sandbox',
						'name' => 'sandbox',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6896ba4d1b5af',
								'label' => 'Merchant\'s username',
								'name' => 'username',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'allow_in_bindings' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_6896ba4d1b5b0',
								'label' => 'Merchant\'s Id',
								'name' => 'merchants_id',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'allow_in_bindings' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_6896ba4d1b5b1',
								'label' => 'Checksum key',
								'name' => 'checksum_key',
								'aria-label' => '',
								'type' => 'password',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'allow_in_bindings' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_6896ba4d1b5b2',
								'label' => 'Url checkout',
								'name' => 'url_checkout',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'allow_in_bindings' => 0,
								'placeholder' => '',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_6846a049a25f6',
				'label' => 'Promotion Box',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_6846a128a25f8',
				'label' => 'Promotion box',
				'name' => 'promotion_box',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'pagination' => 1,
				'rows_per_page' => 20,
				'min' => 0,
				'max' => 0,
				'collapsed' => 'field_6846a1ed4c0a1',
				'button_label' => 'Add Box',
				'sub_fields' => array(
					array(
						'key' => 'field_6846a081a25f7',
						'label' => 'Box style',
						'name' => 'box_style',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'box-style-1' => 'Style 1',
							'box-style-2' => 'Style 2',
							'widget-r' => 'Right widget',
						),
						'default_value' => false,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'allow_in_bindings' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846a1754c09f',
						'label' => 'Box color',
						'name' => 'box_color',
						'aria-label' => '',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 0,
						'return_format' => 'string',
						'allow_in_bindings' => 0,
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846a1b24c0a0',
						'label' => 'Box icon',
						'name' => 'box_icon',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'order-checked' => 'List with checked',
							'gift-solid' => 'gift-solid',
							'map-search' => 'map-search',
							'store' => 'store',
							'store-2' => 'store-2',
							'golf-hole' => 'golf-hole',
							'truck' => 'truck',
							'truck-2' => 'truck-2',
							'hand-dollar' => 'hand-dollar',
							'crown' => 'crown',
							'gift-box' => 'gift-box',
							'percent' => 'percent',
							'location' => 'location',
							'medal' => 'medal',
							'payment' => 'payment',
							'bell' => 'bell',
							'list-search' => 'list-search',
						),
						'default_value' => 'bell',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'allow_in_bindings' => 1,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846a1ed4c0a1',
						'label' => 'Box title',
						'name' => 'box_title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846a1fe4c0a2',
						'label' => 'Box content',
						'name' => 'box_content',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => 'Dùng:<br>
ol class="numberic-list"	 : List dạng đánh Số thứ tự <br>
ul class="checkmark-list" : List dạng checked',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'allow_in_bindings' => 0,
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846a51faa6f2',
						'label' => 'Apply to',
						'name' => 'apply_to',
						'aria-label' => '',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'all' => 'All products',
							'product' => 'Single product',
							'brand' => 'Brand',
							'category' => 'Category',
						),
						'default_value' => array(
							0 => 'all',
						),
						'return_format' => 'value',
						'allow_custom' => 0,
						'allow_in_bindings' => 0,
						'layout' => 'vertical',
						'toggle' => 0,
						'save_custom' => 0,
						'custom_choice_button_text' => 'Thêm lựa chọn mới',
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846a61da640e',
						'label' => 'Brand select',
						'name' => 'brand_select',
						'aria-label' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6846a51faa6f2',
									'operator' => '==',
									'value' => 'brand',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'brands',
						),
						'post_status' => '',
						'taxonomy' => '',
						'return_format' => 'object',
						'multiple' => 1,
						'allow_null' => 0,
						'allow_in_bindings' => 0,
						'bidirectional' => 0,
						'ui' => 1,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846a7c7a640f',
						'label' => 'Category select',
						'name' => 'category_select',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6846a51faa6f2',
									'operator' => '==',
									'value' => 'category',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'pro_cate',
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'object',
						'field_type' => 'multi_select',
						'allow_null' => 1,
						'allow_in_bindings' => 0,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_6846a128a25f8',
					),
					array(
						'key' => 'field_6846bc731ae5d',
						'label' => 'Product SKU',
						'name' => 'product_sku',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6846a51faa6f2',
									'operator' => '==',
									'value' => 'product',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_6846a128a25f8',
					),
				),
			),
			array(
				'key' => 'field_68678575f8389',
				'label' => 'Popup Banner',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_68678756c4785',
				'label' => 'Enable Popup',
				'name' => 'enable_popup',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'allow_in_bindings' => 0,
				'ui_on_text' => 'On',
				'ui_off_text' => 'Off',
				'ui' => 1,
			),
			array(
				'key' => 'field_686785a6f838a',
				'label' => 'Popup banner',
				'name' => 'popup_banner',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_68678756c4785',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_6867866af838d',
						'label' => 'Content',
						'name' => 'content_type',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'allow_in_bindings' => 0,
						'ui_on_text' => 'Text',
						'ui_off_text' => 'HTML Block',
						'ui' => 1,
					),
					array(
						'key' => 'field_68678834c4786',
						'label' => 'Content text',
						'name' => 'content_text',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6867866af838d',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '80',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'allow_in_bindings' => 0,
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 1,
						'delay' => 1,
					),
					array(
						'key' => 'field_6867888cc4787',
						'label' => 'Content block',
						'name' => 'content_block',
						'aria-label' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6867866af838d',
									'operator' => '!=',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '80',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'cms_block',
						),
						'post_status' => array(
							0 => 'publish',
						),
						'taxonomy' => '',
						'return_format' => 'id',
						'multiple' => 0,
						'allow_null' => 0,
						'allow_in_bindings' => 0,
						'bidirectional' => 0,
						'ui' => 1,
						'bidirectional_target' => array(
						),
					),
					array(
						'key' => 'field_68678b1334a16',
						'label' => 'Popup background color',
						'name' => 'popup_background_color',
						'aria-label' => '',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 0,
						'return_format' => 'string',
						'allow_in_bindings' => 0,
					),
					array(
						'key' => 'field_68678fc7676eb',
						'label' => 'Content color',
						'name' => 'content_color',
						'aria-label' => '',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 0,
						'return_format' => 'string',
						'allow_in_bindings' => 0,
					),
					array(
						'key' => 'field_68678b5634a17',
						'label' => 'Background photo',
						'name' => 'background_photo',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'allow_in_bindings' => 0,
						'preview_size' => 'thumbnail',
					),
					array(
						'key' => 'field_68678bc134a18',
						'label' => 'Popup width',
						'name' => 'popup_width',
						'aria-label' => '',
						'type' => 'range',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'default_value' => 400,
						'min' => 400,
						'max' => 1000,
						'allow_in_bindings' => 0,
						'step' => 10,
						'prepend' => '',
						'append' => 'px',
					),
					array(
						'key' => 'field_686796818f63b',
						'label' => 'Hide on mobile',
						'name' => 'hide_on_mobile',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'allow_in_bindings' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
					),
					array(
						'key' => 'field_686796a48f63c',
						'label' => 'Show only one time',
						'name' => 'show_only_one_time',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => 'Only show one time per day',
						'default_value' => 1,
						'allow_in_bindings' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
					),
					array(
						'key' => 'field_6867972dc8b01',
						'label' => 'Popup version',
						'name' => 'popup_version',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'If you apply any changes to your popup settings or content you might want to force the popup to all visitors who already closed it again. In this case, you just need to increase the banner version.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '60',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'min' => 1,
						'max' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'step' => 1,
						'prepend' => '',
						'append' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'site-configs',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	// Register Options Pages
	acf_add_options_page( array(
		'page_title' => 'Homepage',
		'menu_slug' => 'homepage',
		'parent_slug' => 'site-configs',
		'position' => '',
		'redirect' => false,
		'capability' => 'manage_options',
	) );

	acf_add_options_page( array(
		'page_title' => 'Site Configs',
		'menu_slug' => 'site-configs',
		'menu_title' => 'Site Configs',
		'position' => 3,
		'redirect' => false,
		'menu_icon' => array(
			'type' => 'dashicons',
			'value' => 'dashicons-welcome-view-site',
		),
		'update_button' => 'Update',
		'capability' => 'manage_options',
		'icon_url' => 'dashicons-welcome-view-site',
	) );
}
add_action( 'acf/init', 'vcl_register_acf_fields_and_options' );


// This remains on the 'init' hook as it's not ACF-related.
add_action( 'init', function() {
	register_taxonomy( 'pro_cate', array(
		0 => '',
	), array(
		'labels' => array(
			'name' => 'Product Categories',
			'singular_name' => 'Product Category',
			'menu_name' => 'Categories',
			'all_items' => 'All Categories',
			'edit_item' => 'Edit Category',
			'view_item' => 'View Category',
			'update_item' => 'Update Category',
			'add_new_item' => 'Add New Category',
			'new_item_name' => 'New Category Name',
			'parent_item' => 'Parent Category',
			'parent_item_colon' => 'Parent Category:',
			'search_items' => 'Search Categories',
			'not_found' => 'No categories found',
			'no_terms' => 'No categories',
			'filter_by_item' => 'Filter by category',
			'items_list_navigation' => 'Categories list navigation',
			'items_list' => 'Categories list',
			'back_to_items' => '← Go to categories',
			'item_link' => 'Category Link',
			'item_link_description' => 'A link to a category',
		),
		'public' => true,
		'hierarchical' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
		'show_tagcloud' => false,
		'sort' => true,
	) );
} );